export type BrandModelCatalogItem = {
  slug: string;
  name: string;
  models: string[];
};

export const POPULAR_BRAND_MODEL_CATALOG: BrandModelCatalogItem[] = [
  {
    slug: "skoda",
    name: "Skoda",
    models: [
      "Fabia",
      "Octavia",
      "Superb",
      "Kodiaq",
      "Karoq",
      "Kamiq",
      "Scala",
      "Rapid",
      "Enyaq",
      "Roomster",
      "Yeti",
      "Citigo",
    ],
  },
  {
    slug: "bmw",
    name: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "Z4",
      "i3",
      "i4",
      "i5",
      "i7",
      "iX",
    ],
  },
  {
    slug: "audi",
    name: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "e-tron",
      "Q4 e-tron",
      "e-tron GT",
    ],
  },
  {
    slug: "mercedes-benz",
    name: "Mercedes-Benz",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "E-Class",
      "S-Class",
      "CLA",
      "CLS",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "G-Class",
      "V-Class",
      "EQE",
      "EQS",
    ],
  },
  {
    slug: "volkswagen",
    name: "Volkswagen",
    models: [
      "Polo",
      "Golf",
      "Passat",
      "Arteon",
      "T-Cross",
      "T-Roc",
      "Tiguan",
      "Touareg",
      "Touran",
      "Sharan",
      "Caddy",
      "Transporter",
      "Multivan",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.7",
    ],
  },
  {
    slug: "toyota",
    name: "Toyota",
    models: [
      "Aygo",
      "Yaris",
      "Corolla",
      "Camry",
      "C-HR",
      "RAV4",
      "Highlander",
      "Land Cruiser",
      "Prius",
      "Hilux",
      "ProAce",
      "Avensis",
      "Auris",
    ],
  },
  {
    slug: "ford",
    name: "Ford",
    models: [
      "Fiesta",
      "Focus",
      "Mondeo",
      "Mustang",
      "Puma",
      "Kuga",
      "Edge",
      "Explorer",
      "Ranger",
      "Transit",
      "Transit Custom",
      "Tourneo Custom",
      "S-Max",
      "Galaxy",
    ],
  },
  {
    slug: "hyundai",
    name: "Hyundai",
    models: [
      "i10",
      "i20",
      "i30",
      "i40",
      "Elantra",
      "Tucson",
      "Santa Fe",
      "Kona",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
      "Bayon",
    ],
  },
  {
    slug: "kia",
    name: "Kia",
    models: [
      "Picanto",
      "Rio",
      "Ceed",
      "ProCeed",
      "XCeed",
      "Stonic",
      "Niro",
      "Sportage",
      "Sorento",
      "EV6",
      "EV9",
      "Optima",
    ],
  },
  {
    slug: "honda",
    name: "Honda",
    models: [
      "Jazz",
      "Civic",
      "Accord",
      "CR-V",
      "HR-V",
      "ZR-V",
      "e",
      "NSX",
      "Insight",
    ],
  },
  {
    slug: "nissan",
    name: "Nissan",
    models: [
      "Micra",
      "Juke",
      "Qashqai",
      "X-Trail",
      "Leaf",
      "Ariya",
      "Navara",
      "Patrol",
      "GT-R",
    ],
  },
  {
    slug: "volvo",
    name: "Volvo",
    models: [
      "S60",
      "S90",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC90",
      "C40",
      "EX30",
      "EX90",
    ],
  },
  {
    slug: "peugeot",
    name: "Peugeot",
    models: [
      "108",
      "208",
      "2008",
      "308",
      "3008",
      "5008",
      "508",
      "Rifter",
      "Traveller",
      "Partner",
      "Expert",
      "Boxer",
    ],
  },
  {
    slug: "renault",
    name: "Renault",
    models: [
      "Twingo",
      "Clio",
      "Captur",
      "Megane",
      "Arkana",
      "Austral",
      "Kadjar",
      "Espace",
      "Scenic",
      "Kangoo",
      "Trafic",
      "Master",
      "Zoe",
    ],
  },
];
